Page Views by Article ID by day for limited number of days (#21)
* Add PageViewsProvider and integrate into API router and tests

* Refactor PageViewsProvider implementation and update API router integration

* Add unit tests for PageViewsProvider to verify zero page views response

* Integrate Redis client into PageViewsProvider and update tests to reflect changes

* Enhance PageViewsProvider to return sorted page views by date in response

* Refactor citations provider list to accept redis client as a parameter

* Add Redis client mock fixture for CLI tests

* Used Iterator instead of Iterable in test fixtures

* Limit page views returned to the specified per_page count in PageViewsProvider

* Implement pagination for page views in PageViewsProvider and add corresponding tests

* Add refresh_data method to PageViewsProvider and corresponding tests

* Fixed logging message

* Call refresh data on page views provider

* Temporarily limit data range due to it taking too long

* Add tqdm for progress tracking in PageViewsProvider and log total rows from BigQuery

* Fixed tests trying to access total_rows

* Used get_bq_result_from_bq_query in refresh data to be able to log total rows from BigQuery and tqdm progress

* Ignored tqdm __del__ error: 'tqdm' object has no attribute 'last_print_t'

* Add autouse=True to page_views_provider_class_mock fixture to prevent test failure

* updated test for resfresh data and mocked for the test get_bq_result_from_bq_query

* Remove custom tqdm __del__ wrapper to eliminate AttributeError warnings

* Moved refreshing page views to separate CLI

* Renamed citations CLI and corresponding tests

* Update page views query to remove hardcoded date and use dynamic date range

* Added support for dynamic number of days in page views refresh

---------

Co-authored-by: HazalCiplak <hazalciplak@gmail.com>